name: Multi-Job Workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1, Step 1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 2, Step 1"
